### ISSUE TITLE
数据量很大时，wordMap导致内存溢出的问题

### ISSUE THREAD

**Issue by sduchh** [NLPchina/Word2VEC_java#9]
数据量很大的时候，用wordMap存储词的信息会造成Exception in thread "main" java.lang.OutOfMemoryError: Java heap space的问题，请问有什么好的改进方法吗？

**Comment by ansjsun** [comment]
用c语言版 来训练，，java来加载吧。这是个玩具。训练模块最好还用原生的版本

**Comment by sduchh** [comment]
谢谢！


ansj <notifications@github.com>编写：
